### ISSUE TITLE
Cannot change gift icons

### ISSUE THREAD

**Issue by JuneWitch** [tomlaflin/sentiment#11]
When editing a gift on a character sheet, selecting a file to replace the default gift icon will often have no effect. The gift's icon either stays the same, or glitches back to the default icon of two hands around a star after editing other aspects of the gift.

Currently on version 11, build 135 of Foundry VTT. Sentiment version 1.0.8. OS is Windows 11.

**Comment by tomlaflin** [comment]
I can't reproduce this locally. Can you update to the latest release of the Sentiment system, check if you still see this behavior, and if so, capture a video? I want to make sure I'm going through the same UI flow as you.

**Comment by JuneWitch** [comment]
Updating appears to have fixed the issue!!
