### ISSUE TITLE
Cannot Scroll on sheets

### ISSUE THREAD

**Issue by FreyVal** [tomlaflin/sentiment#14]
As the title says in gifts, the description section of sheets and the attribute section sometimes I am unable to scroll. The only way to be able to read more is by making the sheet bigger but for sheets with a very large amount of text this isn't enough. I've tried this with no modules and checked with a different foundry system to ensure that this wasn't just an issue with my foundry.

The only way I have found that I'm able to scroll is by opening the gift sheet in edit. Though for something like the attribute section that isn't possible which could be a large issue for high attribute count enemies

**Comment by Epsi22** [comment]
Also experiencing the same issue.  Including some screenshots below

**Non-edit mode:**

![image](https://github.com/user-attachments/assets/4788afa0-61db-48f0-9406-0ce520efecfb)

**Edit mode:**

![image](https://github.com/user-attachments/assets/31d91cfb-dddd-4439-bf5b-b8f3de676e20)

**Comment by tomlaflin** [comment]
Fixed in release 0.1.4.
