### ISSUE TITLE
Attribute items defaulting to Gift sheet

### ISSUE THREAD

**Issue by Eva096** [tomlaflin/sentiment#2]
When installing the system fresh, it seems like Attributes use the Gift sheet as a default, meaning you can't actually configure them as attributes. Not a hard fix, just open up any attribute sheet and change the default sheet from sentiment.GiftSheet to sentiment.AttributeSheet (this will change it for all Attribute items, gifts will still use the gift sheet).

Not quite sure if this was just an installation issue on my part or not, looking at the template file for attribute sheets it seems like it should be set up right from the get-go.

![Screenshot 2024-01-31 193436](https://github.com/tomlaflin/sentiment/assets/34192414/27a9dea1-793c-4991-86d7-ca8e84f3659c)

**Comment by tomlaflin** [comment]
I'm also able to repro when creating a new world. Need to see if there's something I haven't configured properly with the sheets.

**Comment by tomlaflin** [comment]
Copied the 5E system's homework and it seems to be working by default in newly created worlds now. Thanks for reporting!
