### ISSUE TITLE
Feature Request - Global Roll to Do/dye/recover macro OR Action HUD

### ISSUE THREAD

**Issue by FreyVal** [tomlaflin/sentiment#4]
I'm not sure how possible this would be but something that'd be nice to have would be macros that would make, for example, a Roll to Do based on the selected token(s). Or potentially some sort of in-built action HUD that would handle the same kind of thing and possibly more to reduce the amount of clicking on and between sheets. So far I've only done a solo test combat to try and simulate what it'd be like and I ran into the issue of it being a little clunky with the aforementioned clicking on and between sheets. 

I'm not familiar with coding but I'm sure it'd be quite challenging and take a good amount of time due to the nature of it so no worries if it'd be too much to do! 😄

**Comment by tomlaflin** [comment]
Makes sense as a scenario I'd want to support. I believe modules are able to add new UI to the context menu on a token - maybe I'll look into that first. A global action that acts on the selected token should be workable as a fallback.

**Comment by FreyVal** [comment]
Awesome! Looking forwards to what you come up with 😄

**Comment by tomlaflin** [comment]
Should be nicely addressed by the creation of the Token Action HUD Sentiment module, which you can find here: https://github.com/tomlaflin/fvtt-token-action-hud-sentiment

Requires the v0.2.0 or later release of the Sentiment system module.
