### ISSUE TITLE
Drop Swing - Custom Images

### ISSUE THREAD

**Issue by FreyVal** [tomlaflin/sentiment#5]
Under the attributes section when dropping a swing it seemingly doesn't register and remains displaying whatever the swing was before dropping and when using the custom images per swing option the image doesn't return to the swingless state. Strangely, the Roll to Do option appears to register the swing being dropped and the "swing dropped" chat message still appears as expected. I tested this on multiple sheets just to make sure it wasn't a strange error on a single sheet causing the issue. It doesn't seem to be a very pressing issue since it's being accounted for mechanically though I thought it'd be worth submitting an issue for it.

**Comment by tomlaflin** [comment]
Do you find this happening consistently, every time on every sheet? And are you dropping swing by selecting "None" in the dropdown, or by hitting the Drop Swing button?

**Comment by FreyVal** [comment]
It happens on all sheets including brand new every time. I have been using the Drop Swing button but I also tried editing the swing directly and neither worked - even on creating a fresh token for that sheet with linked actor data and no swing on the sheet the token retains the variant of whatever swing was last locked in.

**Comment by tomlaflin** [comment]
After digging into this, I believe this is the same issue reported by Epsilon and should hopefully also be resolved by commit 44ddea5.
